<div class="container">
    <!-- Page Heading/Breadcrumbs -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Cliente
                <small>Adicionar Cliente</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="/">Home</a></li>
                <li><a href="/cliente">Clientes</a></li>
                <li class="active">Novo</li>
            </ol>
        </div>
    </div>
    <div class="row">
            <form class="form-inline" action="" method="post">
                <div class="form-group">
                    <label for="tipo">Tipo</label>
                    <select class="form-control" name="tipo">
                        <option value="1">Pessoa Física</option>
                        <option value="2">Pessoa Jurídica</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="nome">Nome</label>
                    <input type="text" class="form-control" id="nome" placeholder="Nome completo">
                </div>
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" class="form-control" id="email" placeholder="Email">
                </div>
                <button type="submit" class="btn btn-primary">Salvar</button>
            </form>
    </div>
</div>