<div class="container">
    <!-- Page Heading/Breadcrumbs -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Cliente
                <small>Lista de clientes</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="/">Home</a>
                </li>
                <li class="active">Clientes</li>
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <table id="myTable" class="table  table-responsive tablesorter">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Nome</th>
                    <th>Telefone</th>
                    <th>Email</th>
                </tr>
                </thead>
                <tbody>
                <?php

                foreach ($clientes as $cliente) {
                    echo "<tr>";
                    echo "<td><a href='/cliente?id={$cliente->getCodigo()}'>{$cliente->getCodigo()}</a></td>";
                    echo "<td>{$cliente->getNome()}</td>";
                    echo "<td>{$cliente->getTelefone()}</td>";
                    echo "<td>{$cliente->getEmail()}</td>";

                    echo "</tr>";
                };
                ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="/js/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="/js/bootstrap.min.js"></script>
<script src="/js/jquery.tablesorter.min.js"></script>
<script>
    $(document).ready(function () {
        $(function () {
            $("#myTable").tablesorter();
        });
    });
</script>