<div class="container">
    <!-- Page Heading/Breadcrumbs -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Cliente
                <small>Detalhe de cliente</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="/">Home</a>
                </li>
                <li><a href="/cliente">Clientes</a>
                </li>
                <li class="active"><?php echo $clientes[filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT)]->getNome();?></li>
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 panel-info">
            <div class="row col-lg-12"><b>Tipo:</b> <?php echo  $clientes[filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT)]->getTipo()==1?'PF':'PJ';?></div>
            <div class="row col-lg-12"><b>Nome:</b> <?php echo  $clientes[filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT)]->getNome();?></div>
            <div class="row col-lg-12"><b>Documento:</b> <?php echo $clientes[filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT)]->getDocumento();?></div>
            <div class="row col-lg-12"><b>Fone:</b> <?php echo $clientes[filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT)]->getTelefone();?></div>
            <div class="row col-lg-12"><b>Email:</b> <?php echo $clientes[filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT)]->getEmail();?></div>
            <div class="row col-lg-12"><b>Endere&ccedil;o:</b> <?php echo $clientes[filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT)]->getEndereco();?></div>
        </div>
    </div>
</div>