<div class="container">
    <!-- Page Heading/Breadcrumbs -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Projeto
                <small>
                    Cadastro de clientes
                </small>
            </h1>
            <ol class="breadcrumb">
                <li class="active">Home</li>
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <h1>
                Cadastro de clientes
            </h1>
        </div>
    </div>
</div>