<div class="container">
    <!-- Page Heading/Breadcrumbs -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">404
                <small>P&aacute;gina n&atilde;o encontrada</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="/">Home</a>
                </li>
                <li class="active">404</li>
            </ol>
            <h2 class="error-404">Desculpe-nos</h2>
        </div>


    </div>
</div>
